### ISSUE TITLE
[Suggestion] Add IC2 Replicator and Fluid/Solid Canning Machine handler

### ISSUE THREAD

**Issue by Xen1290** [Elecs-Mods/CMIP#1]
As title says. And.. very good mod! Thanks!

P.S. This mod is fully compatible with WAILA-Plugins(https://github.com/tterrag1098/WAILAPlugins) and WAILA Harvestability(https://github.com/squeek502/WailaHarvestability)? I mean for duplicate handlers or similar.

**Comment by Elec332** [comment]
It should be fully compatible with WAILA Harvestability, there might be duplicate handlers with WAILAPlugins, inwhich case you have 2 options:
-Disable the information that is duplicated <-- Recommended :P
-Remove any of the 2 mods

Ill look into those handlers

**Comment by Xen1290** [comment]
Thanks!

**Comment by Elec332** [comment]
I just got confirmed that the Forestry bee-data (And als engine heat IIRC) 
is also handled by WailaPlugins, you you could disable that part (Other forestry stuff is not IIRC). Also the forge-tankhandler seems to be a duplicate, but that was disabled by default anyways.

**Comment by Xen1290** [comment]
Thanks for the information!

**Comment by Elec332** [comment]
The UU-Matter handler is done, though I keep having issues with making a handler for the Solid/Fluid Canning Machine, and because it can basically do 4 things that are not yet listed in NEI, im putting this on hold for a while.

**Comment by Xen1290** [comment]
Thanks! I'll wait for the other handler.
Yes, but now that fluid/solid canning machine is the basic of ic2exp, (make coolant and other) and wikis are not updated, so anybody don't know that recipes.

**Comment by Elec332** [comment]
Oh, I didnt know that :)
(Havent played it in quite a while)

**Comment by Xen1290** [comment]
@Elec332 http://jenkins.ic2.player.to/job/IC2_experimental/changes
It seems that IC2 has added Fluid canning machine handler! (Finally)

**Comment by Elec332** [comment]
---

I just finished making it (Stupid Github didnt process closing this issue...)

**Comment by Elec332** [comment]
PS: I finished mine 2 hours earlier than IC2

**Comment by Xen1290** [comment]
Oh sorry, i'll see what ic2 has added and compare the two handlers, and github didn't process the closing because you have missed a space.

**Comment by Elec332** [comment]
haha

**Comment by Elec332** [comment]
Ok, so I looked around, and found that the default IC2 handlers has generated quite a few crash-reports, so CMIP now disables the default IC2 handler and replaces it with my one

**Comment by Xen1290** [comment]
Yeah, yours is a lot better. Maybe inform ic2 devs?

**Comment by Xen1290** [comment]
@Elec332 Also, the Replicator handler doesn't appear when I click "R" on an item that should be put in the replicator and the numbers are quite strange:
![2015-10-25_12 40 25](https://cloud.githubusercontent.com/assets/8685029/10715393/bfd01218-7b15-11e5-9fab-0217033cea26.png)
