### ISSUE TITLE
[Question] Forestry support

### ISSUE THREAD

**Issue by accessdenied0** [Elecs-Mods/CMIP#2]
Hey @Elec332,

I recently installed CMIP to my instance. It the Minecraft instance loaded up, but crashed soon as I try to load up a world, It crashes (canceled the world loading). ( http://pastebin.com/qxDrxc3i )

Here now my questions:
- I guess you support Forestry 4.x? I didn't found any hint to the supported versions, so I guess of this crash you support Forestry 4.x, because I use still 3.x (3.6.9.28 to be exact).
- And if this is the case: Do you plan to release a 3.x version? I would like to use this addition but I'm not ready yet to use the newest version of Forestry.

thankful,

access_denied

**Comment by Elec332** [comment]
In my libs folder (https://github.com/Elecs-Mods/CMIP/tree/master/libs), I indeed have forestry 4.0.5

**Comment by Dominance** [comment]
Could a config to disable the entire module be implemented. For thoughts that cannot move to 4.0 due to well yeah just binnie's mods.

**Comment by Elec332** [comment]
This is exactly what I did in my latest commit, Ill probably upload a new version this weekend

**Comment by Dominance** [comment]
Cheers thanks a ton!

**Comment by Elec332** [comment]
Latest release (with options to disable entire mods) is uploaded to curse
(Might not have been approved yet)

Closing this issue
