### ISSUE TITLE
Crash with latest Forestry

### ISSUE THREAD

**Issue by mezz** [Elecs-Mods/CMIP#6]
A crash was reported to me here: https://github.com/ForestryMC/ForestryMC/issues/961

The internal interface CMIP is looking for has moved.
It is now `forestry.core.access.IRestrictedAccess`

This crash occurs even if you disable everything in the Config file.
Please be careful to handle exceptions when integrating with mods' internal code, anything can happen.

Also you may want to check for overlaps with WAILA Plugins, which also displays Forestry information.
http://www.curse.com/mc-mods/minecraft/226119-waila-plugins

**Comment by Elec332** [comment]
I am already merging all waila stuff with @tterrag1098 's WAILAPlugins mod
