### ISSUE TITLE
Don`t create a new world with forestry_1.7.10-4.2.8.56

### ISSUE THREAD

**Issue by Tsyklop** [Elecs-Mods/CMIP#7]
I cant create a new world if install forestry_1.7.10-4.2.0.47.
CMIP-1.7.10-1.0Beta.23

http://pastebin.com/NjsCn9k0

**Comment by BlazingGamer** [comment]
Represented with Forestry 4.2.7.55, CMIP b.23. This appears before world creating

**Comment by Tsyklop** [comment]
please. fix this
